name: Nasadiť DEV na ACC

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: promote-dev-to-acc
  cancel-in-progress: true

jobs:
  deploy-acceptance:
    runs-on: ubuntu-latest
    steps:
      - name: Načítať vetvu dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Aktualizovať vetvu acc
        run: |
          git push origin HEAD:acc
